# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Michael Scholze
paginate:         1
baseurl:          /

author:
  name:           Michael Scholze

# Custom vars
pages_list:       
  Blog: '/blog'
  About: '/about'
  Contact: '/contact'